### ISSUE TITLE
No Longer Maintained

### ISSUE THREAD

**Issue by Zain-ul-din** [IIvexII/LGU-TimetableAPI#110]
## Proposal

Since we're providing LGU APIS through from website this repository can be **ambiguous** for users that's why I propose to add a `no longer maintained` alert and redirect to our [website](https://www.lgutimetable.live/) on the top of the readme.md

### [Developer Section Link](https://www.lgutimetable.live/developer)

**Comment by IIvexII** [comment]
Thanks for mentioning it. It is merged (#111)
