### ISSUE TITLE
Repo clone is not working

### ISSUE THREAD

**Issue by Zain-ul-din** [IIvexII/LGU-TimetableAPI#33]
![image](https://user-images.githubusercontent.com/78583049/199709500-2bcafc74-6115-4015-84b2-965ebd7718c6.png)

Why i am not able to clone your repo ?

**Comment by Zain-ul-din** [comment]
Now I get all files but the ` invalid path 'docs/How_to_get_session?.md`  error is still there

**Comment by Zain-ul-din** [comment]
Or one more thing how can i meet you in uni ?

**Comment by IIvexII** [comment]
Please fork the repo and clone it from your side.

**Comment by Zain-ul-din** [comment]
I did this but error is not gone

**Comment by Zain-ul-din** [comment]
Can I have your whats app number?

**Comment by Zain-ul-din** [comment]
I have panned to cache lgu time table on our side so anyone can see time table in less time

**Comment by IIvexII** [comment]
Please specify OS and git version.

**Comment by Zain-ul-din** [comment]
Window 10 
git version 2.37.1.windows.1

**Comment by IIvexII** [comment]
In Windows '?' is an invalid character in filename. I didn't consider that at the time of making that doc. I have fixed it now. Please try to clone it now.

**Comment by Zain-ul-din** [comment]
can i have your whats app number ?

**Comment by IIvexII** [comment]
Sorry I cannot Share it here but you can email me to have my number.

**Comment by Zain-ul-din** [comment]
ok

**Comment by Zain-ul-din** [comment]
Please contact me here +92 311 6287297

**Comment by Zain-ul-din** [comment]
tell me when you read this post so i can delete this from here

**Comment by IIvexII** [comment]
You can delete it now.
