### ISSUE TITLE
'Technologies Used'  are mentioned wrong in README.md.

### ISSUE THREAD

**Issue by IIvexII** [IIvexII/LGU-TimetableAPI#35]
**Description**
If it's you are looking to contribute, this issue will get you started.

**Technologies Used**
- Node.js
- Express.js
- JavaScript

**Comment by Pragya2056** [comment]
Please assign this to me

**Comment by Pragya2056** [comment]
This issue was worked on the PR #37

**Comment by Pragya2056** [comment]
@IIvexII 
please review it.
