### ISSUE TITLE
Fix the download link that point to v1.0

### ISSUE THREAD

**Issue by IIvexII** [IIvexII/LGU-TimetableAPI#54]
This issue is for you if you have never contributed to open source project or just started your journey in it. I encourage you to fix this and make a pull request. Here is the image of document that needs to be fixed.

![image](https://user-images.githubusercontent.com/41378765/200835388-3d90e65b-89d5-4bbc-af74-5f7b845a754d.png)

Replace the download link with this https://github.com/IIvexII/LGU-TimetableAPI/releases

**Comment by trieu099** [comment]
![image](https://user-images.githubusercontent.com/96922130/201907834-5d2323b4-03a2-465e-bbcf-48c063d00ab2.png)
I already update README.md file, it's ok?
