### ISSUE TITLE
Separate the GET and the route name in routes column into two different columns

### ISSUE THREAD

**Issue by IIvexII** [IIvexII/LGU-TimetableAPI#76]
# Issue

If you want to contribute but don't know where to start, this is the issue for you to get started. Make a **separate column for Method** and remove them from **Route** column.

![image](https://user-images.githubusercontent.com/41378765/201809673-4552940c-1064-484b-9096-20015f0fc4ae.png)

Like this,

![image](https://user-images.githubusercontent.com/41378765/201810164-14281fdc-487e-4434-9093-2c11fcb79013.png)

**Comment by 11qqqq11** [comment]
![image](https://user-images.githubusercontent.com/95013554/201902684-03ac1714-ceeb-4e78-8a2c-01f2bd518c7a.png)
So the readme.md should be modified like this?
