### ISSUE TITLE
[DOC]: Replace the list of technologies used in README.md with their logos

### ISSUE THREAD

**Issue by IIvexII** [IIvexII/LGU-TimetableAPI#84]
# Changes Suggested

* Replace the list of technologies used in [README.md](https://github.com/IIvexII/LGU-TimetableAPI/blob/main/README.md) with their official logos

![image](https://user-images.githubusercontent.com/41378765/202888105-36c562f6-18ec-4694-9e71-5764cb147fbc.png)

* Change the text

> This software uses the following open source packages:

to 

> Technologies used in this project are:

Or you can use your line that is more appropriate at this point.

**Comment by gogoiakash2311** [comment]
Hey @IIvexII Can you assign this to me

**Comment by IIvexII** [comment]
Hey @gogoiakash2311 I have assigned it to you. You can work on it now.

**Comment by gogoiakash2311** [comment]
Okay

**Comment by IIvexII** [comment]
@gogoiakash2311  Have you started working on it? If you need help, do let me know.

**Comment by gogoiakash2311** [comment]
@IIvexII While setting up the project locally, After running "npm start" it's showing:
There is an error while connecting to database.

**Comment by IIvexII** [comment]
> @IIvexII While setting up the project locally, After running "npm start" it's showing: There is an error while connecting to database.

Bro, there is no need to setup the project at all. Because you are just working on docs. Just work on the required changes. Don't worry about the codebase.

**Comment by gogoiakash2311** [comment]
Okay
