### ISSUE TITLE
[DOC] Add newly created routes in ReadMe.md

### ISSUE THREAD

**Issue by IIvexII** [IIvexII/LGU-TimetableAPI#99]
# Instructions for Contributors

While I am working on the new features of this project, I need someone who can document the routes, that I recently created, in the [ReadMe.md](https://github.com/IIvexII/LGU-TimetableAPI#routes).

## Routes

`/days`, `/rooms`  and `/freeRooms`

## Method

All routes support **GET** method.

# Params

`/freeRooms` route can have **day** and **time** as parameter but both of them are optional. All other routes are parameter less.

## Description

`/days`   -  return all days of week with their id used in official timetable
`/rooms`     -    return all rooms available in the university
`/freeRooms`  -  give the rooms that doesn't not have lecture in it

## Demo links

- https://lgu-timetable-api.deta.dev/days
- https://lgu-timetable-api.deta.dev/rooms
- https://lgu-timetable-api.deta.dev/freeRooms?day=Monday&time=12:40

**Comment by Vinitvh** [comment]
Hi @IIvexII, can I work on this?

**Comment by IIvexII** [comment]
> Hi @IIvexII, can I work on this?

Yeah sure!
